== ODS.2 - Service Period (CWE)

[segment-definition]
When blank, the modifier applies to all service periods. Diet orders, for example, typically apply to all service periods. This field usually specifies supplements. This field allows you to designate a modification for one or more of the service periods during a day by combining service specifications as needed. The service periods will be local CEs, normally numbers. Suggested are:

[segment-comment]
Definition: When blank, the modifier applies to all service periods. Diet orders, for example, typically apply to all service periods. This field usually specifies supplements. This field allows you to designate a modification for one or more of the service periods during a day by combining service specifications as needed. The service periods will be local CEs, normally numbers. Suggested are:
|===
|service 1 |is |breakfast
|service 2 |is |mid-morning snack
|service 3 |is |lunch
|service 4 |is |mid-afternoon snack
|service 5 |is |dinner
|service 6 |is |bedtime snack
|===

Ex: |1~5| means service 1 and service 5, whatever these are locally defined to be.

Refer to Table 0627 - Service Period in Chapter 2C for valid values.
