== DEV.3 - Device Type (CNE)

[segment-definition]
This field contains the type of device used in the participation.

[segment-comment]
See Externally HL7 defined 0961 in Chapter 2C for a list of suggested values. This field can repeat.

When intended to have the additional device information for the device referenced in a PRT segment in the message, DEV-2 must be equal to PRT-10 Device. When PRT-22 Device Type is used, DEV-3 must be equal.

When communicating a UDI Carrier, the UDI may either be uniquely identifying an instance of a device, or a type of device. This can be asserted based on the inclusion or absence of a serial number in the Product Identifier section of the UDI. When the serial number is present, PRT-10 must be used, while if it is absent, PRT-22 must be used.

When communicating a UDI Carrier in this field, the coding system used is limited to FDA (FDAUDI), HIBCC (HIBUDI), ICCBBA (ICCUDI), and GS1 (GS1UDI) coding systems defined in {{v2-table:0396:}}.

Condition: Either DEV-2 Unique Device Identifier or DEV-3 Device Type must be valued, or both are valued.
