Logical: ECD
Parent: $Segment
Id: ECD
Title: "HL7 v2 ECD Segment Definition"
* ^meta.profile = "http://hl7.org/v2/StructureDefinition/Segment-Profile"
* ^date = "2025-06-11T19:08:38Z"
* . ^short = "Equipment Command"
* 1 1..1 NM "ECD-1" "This field contains the unique identifier for this particular command that should be used by the various components for future referral to this command. It is similar to the concept of _MSH-10 Message Control ID_, but at the equipment command/response level. This number is generated by the originator of this command."
* 1 ^extension[0].url = "http://hl7.org/fhir/StructureDefinition/optionality"
* 1 ^extension[=].valueCode = #R
* 1 ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/conformance-length"
* 1 ^extension[=].extension[0].url = "length"
* 1 ^extension[=].extension[=].valueInteger = "10"
* 1 ^extension[=].extension[+].url = "noTruncate"
* 1 ^extension[=].extension[=].valueInteger = false
* 1 ^code.system = "http://hl7.org/v2/CodeSystem/DataElements"
* 1 ^code.code = #1390
* 2 1..1 CWE "ECD-2" "This field identifies the command that the component is to initiate. Refer to _file:///E:\\V2\\v2.9%20final%20Nov%20from%20Frank\\V29_CH02C_Tables.docx#HL70368[User-defined Table 0368 – Remote Control Comman]d_ in Chapter 2C, Code Tables, for valid values. Refer to LECIS standard for details."
* 2 from http://terminology.hl7.org/ValueSet/v2-0368 (required)
* 2 ^extension[0].url = "http://hl7.org/fhir/StructureDefinition/optionality"
* 2 ^extension[=].valueCode = #R
* 2 ^code.system = "http://hl7.org/v2/CodeSystem/DataElements"
* 2 ^code.code = #1391
* 3 0..1 ID "ECD-3" "This field identifies the mode of synchronization that is to be used in relation to the execution of the command. \"Y\" (Yes) means that the response is required immediately after execution; \"N\" (No) response is not required at all. Refer to file:///E:\\V2\\v2.9%20final%20Nov%20from%20Frank\\V29_CH02C_Tables.docx#HL70136[_HL7 Table 0136 – Yes/no Indicator_] for valid values."
* 3 from http://terminology.hl7.org/ValueSet/v2-0136 (required)
* 3 ^extension[0].url = "http://hl7.org/fhir/StructureDefinition/optionality"
* 3 ^extension[=].valueCode = #O
* 3 ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/length"
* 3 ^extension[=].extension[0].url = "min"
* 3 ^extension[=].extension[=].valueInteger = 1
* 3 ^extension[=].extension[+].url = "max"
* 3 ^extension[=].extension[=].valueInteger = 1
* 3 ^code.system = "http://hl7.org/v2/CodeSystem/DataElements"
* 3 ^code.code = #1392
* 4 0..1 BackboneElement "ECD-4" "ECD-4"
* 4 ^extension[0].url = "http://hl7.org/fhir/StructureDefinition/optionality"
* 4 ^extension[=].valueCode = #W
* 4 ^code.system = "http://hl7.org/v2/CodeSystem/DataElements"
* 4 ^code.code = #1393
* 4 ^comment = "*_Attention: As of version 2.5 this fieldwas retained for backward compatibility only and withdrawn as of v2.7._* The TQ data type was deprecated; see Chapter 2A, section 2.A.81. Instead use the \"Explicit time\" (TQ1-4) or \"Relative Time and Units\" (TQ1-5) fields of the TQ1 segment in a message using ECD segment."
* 5 0..0 TX "ECD-5" "This field identifies the parameters of the command (if they are not included in a separate segment(s))."
* 5 ^extension[0].url = "http://hl7.org/fhir/StructureDefinition/optionality"
* 5 ^extension[=].valueCode = #O
* 5 ^code.system = "http://hl7.org/v2/CodeSystem/DataElements"
* 5 ^code.code = #1394
* 5 ^comment = "*Note:* Elements of this segment (or other elements not defined here) may be required for certain vendor-specific equipment such as centrifuges, aliquoters, sorters, uncappers, recappers, automated storage units, etc."