Logical: NDS
Parent: $Segment
Id: NDS
Title: "HL7 v2 NDS Segment Definition"
* ^meta.profile = "http://hl7.org/v2/StructureDefinition/Segment-Profile"
* ^date = "2025-06-11T19:08:38Z"
* . ^short = "Notification Detail"
* 1 1..1 NM "NDS-1" "This field contains a unique sequential reference number that may be used by various components to refer to this transaction. This number is generated by the originator of this notification."
* 1 ^extension[0].url = "http://hl7.org/fhir/StructureDefinition/optionality"
* 1 ^extension[=].valueCode = #R
* 1 ^extension[+].url = "http://hl7.org/fhir/StructureDefinition/conformance-length"
* 1 ^extension[=].extension[0].url = "length"
* 1 ^extension[=].extension[=].valueInteger = "10"
* 1 ^extension[=].extension[+].url = "noTruncate"
* 1 ^extension[=].extension[=].valueInteger = false
* 1 ^code.system = "http://hl7.org/v2/CodeSystem/DataElements"
* 1 ^code.code = #1398
* 2 1..1 DTM "NDS-2" "This field is the date/time of the notifications."
* 2 ^extension[0].url = "http://hl7.org/fhir/StructureDefinition/optionality"
* 2 ^extension[=].valueCode = #R
* 2 ^code.system = "http://hl7.org/v2/CodeSystem/DataElements"
* 2 ^code.code = #1399
* 3 1..1 CWE "NDS-3" "The severity of the specific notification. Refer to file:///E:\\V2\\v2.9%20final%20Nov%20from%20Frank\\V29_CH02C_Tables.docx#HL70367[_HL7 Table 0367 – Alert Level_] in Chapter 2C, Code Tables, for valid entries."
* 3 from http://terminology.hl7.org/ValueSet/v2-0367 (required)
* 3 ^extension[0].url = "http://hl7.org/fhir/StructureDefinition/optionality"
* 3 ^extension[=].valueCode = #R
* 3 ^code.system = "http://hl7.org/v2/CodeSystem/DataElements"
* 3 ^code.code = #1400
* 4 1..1 CWE "NDS-4" "This field contains information about the type of notification being sent. These are manufacturer and equipment specific error or status codes, e.g., AQN0123 – aliquoting error – clot detected. Refer to Table 0610 - Notification Code in Chapter 2C for valid values."
* 4 from http://terminology.hl7.org/ValueSet/v2-0610 (required)
* 4 ^extension[0].url = "http://hl7.org/fhir/StructureDefinition/optionality"
* 4 ^extension[=].valueCode = #R
* 4 ^code.system = "http://hl7.org/v2/CodeSystem/DataElements"
* 4 ^code.code = #1401