== AIP.3 - Personnel Resource ID (XCN)

[segment-definition]
This field contains the ID number and name of the person being requested or scheduled for an appointment. This field is used to identify a specific person being requested, or a specific person who has been scheduled as a resource for an appointment. If the specific person is not known, but the type of resource is, _AIP-4 Resource Type_ is used to identify the type of personnel resource required or scheduled. At a minimum, the ID number component should be supplied to identify either the specific person being requested or the specific person who has been scheduled. For inter-enterprise communications, for which a shared ID number may not be available, the minimum components needed to uniquely identify a person may be defined by site-specific negotiations.

[segment-comment]
This field is conditionally required for this segment. In new schedule request messages, it is required if the request asks that a specific person be scheduled. For all other request messages, the specific person should be identified if the information is available (either because a specific person was initially requested, or because the filler application returned the ID of the specific person who has been scheduled).

This field is required for all unsolicited transactions from the filler application. This field is optional for all query transactions.
