== PID.5 - Patient Name (XPN)

[segment-definition]
This field contains one or more of the names of the patient. The XPN.7 Name Type Code, and not the order, conveys how the name should be interpreted. As of v2.7, Name Type Code is Required. Refer to {{v2-table:0200:Name Type}} in Chaper 2C, Code Tables, for valid values. Specification of meaning based on sequence is deprecated.

[segment-comment]
In addition to allowing repetition of this field for transmitting multiple names with different Name Type Codes, repetition also allows for representing the same name in different character sets based on the value in XPN.8 Name Representation Code.

In order to support “name to use” to indicate how to address the patient, when that does not match their legal name, include an occurrence of Patient Name (PID-5), where the nametype code (PID-5.7) is valued ‘N’.Multiple given names and/or initials are separated by spaces.

For animals, if a Name Type of "R" is used, use "Name Context" to identify the authority with which the animal's name is registered.
