== APR.1 - Time Selection Criteria (SCV)

[segment-definition]
This field is used to communicate parameters and preferences to the filler application regarding the selection of an appropriate time slot for an appointment. The first component of this field is a code identifying the parameter or preference being passed to the filler application. The second component is the actual data value for that parameter.

[segment-comment]
For example, if a filler application allows preference parameters to be passed to specify a preferred start time, a preferred end time, and preferred days of the week for the appointment, it may define the parameter class codes and valid data sets based on suggested codes from {{v2-table:0294:Time Selection Criteria Parameter Class Codes}} in Chapter 2C, Code Tables, for suggested values.

Given the set of parameter class codes and valid value sets from User-Defined table 0294, a placer may indicate a preferred start time of 8:00 AM on Monday, Wednesday or Friday by specifying the following in _APR-1 Time Selection Criteria_:

...|PREFSTART^0800~MON^OK~WED^OK~FRI^OK~TUE^NO~THU^NO~SAT^NO~SUN^NO|...

The valid set of preferences should be determined by the placer and filler applications during implementation of the interface.
