== ORC.16 - Order Control Code Reason (CWE)

[segment-definition]
This field contains the explanation (either in coded or text form) of the reason for the order event described by the order control code ({{v2-table:0119:Order control codes}}). Whereas an NTE after the order-specific segment (e.g., RXO, ORO, OBR) would provide a comment for that specific segment, the purpose of the order control code reason is only to expand on the reason for the order event.

[segment-comment]
ORC-16-order control code reason is typically not valued when ORC-1-order control is NW, although it could be. In the case of a canceled order, for example, this field is commonly used to explain the cancellation. A Pharmacy system that canceled a drug order from a physician because of a well-documented allergy would likely report the fact of the allergy in this field.

If it canceled the order because of a drug interaction this field might contain at least the names (and codes, if needed) of the interacting substances, the text describing the interaction, and the level of severity of the interaction.

Refer {{v2-table:0949:Order Control Code Reason}} in Chapter 2C, Code Tables__.__
