#!/usr/bin/env bash
set -euo pipefail

# Push to Build Branch
#
# Copies IG Publisher-relevant files from main into the 'build' branch,
# runs preprocessing, commits the results, and pushes to origin.
#
# Always pulls from main. The intended workflow is:
#   1. Work on dev/framework or topic branches
#   2. Merge into main when ready (after local build testing)
#   3. Run this script to publish via auto-ig-builder
#
# Only the files the auto-ig-builder needs are copied (input/,
# local-template/, IG Publisher scripts). Development artifacts
# (tooling/, test/, website/, docs/, etc.) never touch the build branch.
#
# Usage:
#   ./push-to-build.sh                    # preprocess locally
#   ./push-to-build.sh --remote           # preprocess on postproc-g (faster)
#   ./push-to-build.sh --no-preprocess    # skip preprocessing (just copy and push)
#
# Prerequisites:
#   - 'build' branch must already exist (created once with ig.ini)
#   - For --remote: SSH access to postproc-g.nist.gov with Apptainer image built
#   - For local preprocessing: Python 3, Ruby, Asciidoctor gem

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "${SCRIPT_DIR}"

# Parse arguments
SOURCE_BRANCH="main"
USE_REMOTE=false
SKIP_PREPROCESS=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --remote)       USE_REMOTE=true; shift ;;
        --no-preprocess) SKIP_PREPROCESS=true; shift ;;
        -h|--help)
            sed -n '3,21p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

# Ensure working tree is clean
if ! git diff --quiet || ! git diff --cached --quiet; then
    echo "Error: working tree has uncommitted changes. Commit or stash first." >&2
    exit 1
fi

ORIGINAL_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
echo "=== Push to Build ==="
echo "  Source: main → build"
echo "  Remote preprocessing: ${USE_REMOTE}"
echo ""

# Step 1: Switch to build branch and copy files from source
echo "--- Copying IG Publisher files from ${SOURCE_BRANCH}... ---"
git checkout build

# Copy only the paths the auto-ig-builder needs
git checkout "${SOURCE_BRANCH}" -- \
    input/ \
    local-template/ \
    _genonce.sh _gencontinuous.sh \
    _genonce.bat _gencontinuous.bat \
    _updatePublisher.sh _updatePublisher.bat \
    .gitignore \
    2>&1 || {
    echo "Error copying files from ${SOURCE_BRANCH}." >&2
    git checkout "${ORIGINAL_BRANCH}"
    exit 1
}
echo "  Files copied from ${SOURCE_BRANCH}"
echo ""

# Step 2: Run preprocessing (needs tooling/ from source branch temporarily)
if [ "$SKIP_PREPROCESS" = true ]; then
    echo "--- Skipping preprocessing (--no-preprocess) ---"
elif [ "$USE_REMOTE" = true ]; then
    echo "--- Preprocessing on postproc-g... ---"
    # Temporarily check out the preprocessing scripts
    git checkout "${SOURCE_BRANCH}" -- tooling/preprocess.sh apptainer/remote-build.sh
    ./apptainer/remote-build.sh preprocess-fetch
    # Remove the temp scripts from staging
    git rm -f --cached tooling/preprocess.sh apptainer/remote-build.sh 2>/dev/null || true
    rm -f tooling/preprocess.sh apptainer/remote-build.sh
    rmdir tooling 2>/dev/null || true
    rmdir apptainer 2>/dev/null || true
else
    echo "--- Preprocessing locally... ---"
    # Temporarily check out tooling for preprocessing
    git checkout "${SOURCE_BRANCH}" -- tooling/
    # Set up Ruby env if available
    if [ -d "/home/claude/ruby/arm64" ]; then
        export LD_LIBRARY_PATH="/home/claude/ruby/arm64/lib:${LD_LIBRARY_PATH:-}"
        export GEM_HOME="/tmp/gems"
        export GEM_PATH="/tmp/gems:/home/claude/ruby/arm64/lib/ruby/gems/3.2.0"
    fi
    bash tooling/preprocess.sh
    # Remove tooling from staging — it shouldn't be committed to build
    git rm -rf --cached tooling/ 2>/dev/null || true
    rm -rf tooling/
fi
echo ""

# Step 3: Stage the updated files
echo "--- Staging files... ---"
git add input/ local-template/
git add _genonce.sh _gencontinuous.sh _genonce.bat _gencontinuous.bat \
    _updatePublisher.sh _updatePublisher.bat .gitignore 2>/dev/null || true

# Check if there's anything to commit
if git diff --cached --quiet; then
    echo "No changes to commit."
else
    CHANGED=$(git diff --cached --stat | tail -1)
    echo "  ${CHANGED}"

    git commit -m "$(cat <<EOF
Update from ${SOURCE_BRANCH}

Auto-generated by push-to-build.sh.

Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>
EOF
)"
fi
echo ""

# Step 4: Push
echo "--- Pushing build branch... ---"
git push origin build
echo ""

# Step 5: Return to original branch
git checkout "${ORIGINAL_BRANCH}"

echo "=== Done. Build branch pushed to origin. ==="
echo "  Monitor: https://build.fhir.org/ig/HL7/v2ig/branches/build/"
