#!/usr/bin/env bash
set -euo pipefail

# Push to Build Branch
#
# Turnkey script that merges the current (or specified) branch into 'build',
# runs preprocessing, commits the results, and pushes to origin.
#
# Usage:
#   ./push-to-build.sh                    # merge current branch, preprocess locally
#   ./push-to-build.sh --remote           # preprocess on postproc-g (faster)
#   ./push-to-build.sh --branch main      # merge a specific branch
#   ./push-to-build.sh --no-preprocess    # skip preprocessing (just merge and push)
#
# Prerequisites:
#   - 'build' branch must already exist (created once with ig.ini)
#   - For --remote: SSH access to postproc-g.nist.gov with Apptainer image built
#   - For local preprocessing: Python 3, Ruby, Asciidoctor gem

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "${SCRIPT_DIR}"

# Parse arguments
SOURCE_BRANCH=""
USE_REMOTE=false
SKIP_PREPROCESS=false

while [[ $# -gt 0 ]]; do
    case "$1" in
        --remote)       USE_REMOTE=true; shift ;;
        --no-preprocess) SKIP_PREPROCESS=true; shift ;;
        --branch)       SOURCE_BRANCH="$2"; shift 2 ;;
        -h|--help)
            sed -n '3,13p' "$0" | sed 's/^# \?//'
            exit 0
            ;;
        *)
            echo "Unknown option: $1" >&2
            exit 1
            ;;
    esac
done

# Determine source branch
if [ -z "$SOURCE_BRANCH" ]; then
    SOURCE_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
fi

if [ "$SOURCE_BRANCH" = "build" ]; then
    echo "Error: source branch cannot be 'build' (that's the target)." >&2
    exit 1
fi

# Ensure working tree is clean
if ! git diff --quiet || ! git diff --cached --quiet; then
    echo "Error: working tree has uncommitted changes. Commit or stash first." >&2
    exit 1
fi

ORIGINAL_BRANCH="$(git rev-parse --abbrev-ref HEAD)"
echo "=== Push to Build ==="
echo "  Source: ${SOURCE_BRANCH}"
echo "  Remote preprocessing: ${USE_REMOTE}"
echo ""

# Step 1: Switch to build branch and merge
echo "--- Merging ${SOURCE_BRANCH} into build... ---"
git checkout build
MERGE_RESULT=$(git merge "${SOURCE_BRANCH}" --no-edit 2>&1) || {
    echo "Merge conflict! Resolve manually on the build branch." >&2
    exit 1
}
echo "$MERGE_RESULT"
echo ""

# Step 2: Run preprocessing
if [ "$SKIP_PREPROCESS" = true ]; then
    echo "--- Skipping preprocessing (--no-preprocess) ---"
elif [ "$USE_REMOTE" = true ]; then
    echo "--- Preprocessing on postproc-g... ---"
    ./apptainer/remote-build.sh preprocess-fetch
else
    echo "--- Preprocessing locally... ---"
    # Set up Ruby env if available
    if [ -d "/home/claude/ruby/arm64" ]; then
        export LD_LIBRARY_PATH="/home/claude/ruby/arm64/lib:${LD_LIBRARY_PATH:-}"
        export GEM_HOME="/tmp/gems"
        export GEM_PATH="/tmp/gems:/home/claude/ruby/arm64/lib/ruby/gems/3.2.0"
    fi
    bash tooling/preprocess.sh
fi
echo ""

# Step 3: Stage preprocessed output
echo "--- Staging preprocessed files... ---"
git add input/pagecontent/ input/includes/
git add input/images/*.png 2>/dev/null || true
git add input/v2plus.xml input/v2plus-subset.xml 2>/dev/null || true

# Check if there's anything to commit
if git diff --cached --quiet; then
    echo "No preprocessing changes to commit."
else
    CHANGED=$(git diff --cached --stat | tail -1)
    echo "  ${CHANGED}"

    git commit -m "$(cat <<EOF
Update preprocessed content from ${SOURCE_BRANCH}

Auto-generated by push-to-build.sh. Includes segment intro pages,
message/structure intro pages, domain pages, and images.

Co-Authored-By: Claude Opus 4.6 (1M context) <noreply@anthropic.com>
EOF
)"
fi
echo ""

# Step 4: Push
echo "--- Pushing build branch... ---"
git push origin build
echo ""

# Step 5: Return to original branch
git checkout "${ORIGINAL_BRANCH}"

echo "=== Done. Build branch pushed to origin. ==="
echo "  Monitor: https://build.fhir.org/ig/HL7/v2ig/branches/build/"
