== PV1.2 - Patient Class (CWE)

[segment-definition]
This field is used by systems to categorize patients by site. It does not have a consistent industry-wide definition. It is subject to site‑specific variations. Refer to {{v2-table:0004:Patient Class}} in Chapter 2C, Code Tables, for suggested values.

[segment-comment]
"Commercial Account" is used by reference labs for specimen processing when the service is billed back to a third party. A registration is processed for the specimen to facilitate the subsequent billing. The identity of the patient may be known or unknown. In either case, for billing and statistical purposes, the patient class is considered a commercial account due to the third party billing responsibility.

"Not Applicable" is used only in cases where the PV1 segment itself is not applicable but is retained in the message definitions for backwards compatibility (for example when a managed care system sends A28, A29, or A31 messages to indicate the enrolment of a patient in the system and there is no scheduled "visit" or "encounter" and hence the entire PV1 segment is not applicable).
