== XCN.9 - Assigning Authority (HD)

[datatype-definition]
The assigning authority is a unique identifier of the system (or organization or agency of department) that creates the data. {{v2-table:0363:Assigning Authority}} is used as the HL7 identifier for the user-defined table of values for the first sub-component of the HD component, <namespace ID>.

As of v 2.7, the Assigning Authority is conditional. It is required if _XCN.1_ is populated and neither _XCN.22_ nor _XCN.23_ are populated. All 3 components may be populated. No assumptions can be safely made based on position or sequence. Best practice is to send an OID in this component when populated.

The reader is referred to _XCN.22_ and _XCN.23_ if there is a need to transmit values with semantic meaning for an assigning jurisdiction or assigning department or agency in addition to, or instead of, an assigning authority. However, all 3 components may be valued. If, in so doing, it is discovered that the values in _XCN.22_ and/or _XCN.23_ conflict with _XCN.9_, the user would look to the Message Profile or other implementation agreement for a statement as to which takes precedence.

[NOTE]
When the HD data type is used in a given segment as a component of a field of another data type, {{v2-table:0300:Namespace ID}} (referenced by the first sub-component of the HD component) may be re-defined (given a different user-defined table number and name) by the technical committee responsible for that segment.

By site agreement, implementors may continue to use {{v2-table:0300:Namespace ID}} for the first sub-component.

