== STF.39 - Generic resource type or category (CWE)

[segment-definition]
This field transmits a code that represents a high level categorization of resources. This is a companion field for the _STF-4 Staff Type_ and allows an institution or enterprise to impose [line-through]#a# one or more super category levels. Refer to {{v2-table:0771:Resource Type or Category}} in Chapter 2C, Code Tables, for suggested values. This table contains no suggested values.

[segment-comment]
An enterprise might have more than one method to categorize or type resources at a high level. Therefore, this field can repeat.

Example: An organization may define discreet staff types (e.g., Pediatric Oncologist, Gerontologist, Oncology Pharmacist, Pediatric Pharmacist, Critical Care Nurse, Nurse Case Manager – Cardiology) as well as broad categories (e.g., Physician, Pharmacist, Nurse, Pediatric, Oncology, Cardiology, Case Management, Nephrology). Employing STF-4 for the discreet terms and STF-39 for the more generic terms allows both the levels of granularity to be apply to the staff without confusing the specific types with generic types. Thus, one may see:

Example: An organization may define discreet staff types (e.g., Pediatric Oncologist, Gerontologist, Oncology Pharmacist, Pediatric Pharmacist, Critical Care Nurse, Nurse Case Manager – Cardiology) as well as broad categories (e.g., Physician, Pharmacist, Nurse, Pediatric, Oncology, Cardiology, Case Management, Nephrology). Employing STF-4 for the discreet terms and STF-39 for the more generic terms allows both the levels of granularity to be apply to the staff without confusing the specific types with generic types. Thus, one may see:
|===
|STF-4 |STF-39
|• Custodian |• Staff
|• Non-clinical Nursing Supervisor |• Manager
|• Pediatric Oncologist |• Physician ~ Pediatrics ~ Oncology
|• Gerontologist |• Physician
|• Oncology Pharmacist |• Pharmacist ~ Oncology
|• Pediatric Pharmacist |• Pediatrics ~ Pharmacist
|• Critical Care Nurse |• Nurse
|• Nurse Case Manager – Cardiology |• Nurse ~ Cardiology ~ Case Management
|===
