== AIL.3 - Location Resource ID (PL)

[segment-definition]
This field contains a coded identification of the location being requested or scheduled for an appointment. This field is used to identify a specific location being requested, or a specific location that has been scheduled for an appointment. If the specific location is not known but the type of location is, _AIL-4-Location Type-AIL_ is used to identify the type of location required or scheduled. This field is conditionally required for this segment. In new schedule request messages, it is required if the request asks that a specific location be scheduled. For all other request messages, the specific location should be identified if the information is available (either because a specific location was initially requested, or because the filler application returned the coded identification of the specific location that has been scheduled).

[segment-comment]
This field is repeating in order to accommodate both local and enterprise-wide identifiers.

This field is required for all unsolicited transactions from the filler application. It is optional for all query transactions.
