== TQ2.7 - Cyclic Entry/Exit Indicator (ID)

[segment-definition]
Indicates if this service request is the first, last, service request in a cyclic series of service requests. If null or not present, this field indicates that the current service request is neither the first or last service request in a cyclic series of service requests. Refer to {{v2-table:0505:Cyclic Entry/Exit Indicator}} in Chapter 2C, Code Tables, for allowed values.

[segment-comment]
Conditional Rule: Should not be populated when TQ2-2 (Sequence/Results Flag) is not equal to a 'C' (cyclic service request).

Example of TQ2 - 6, 7, & 8 Usage:

Example of TQ2 - 6, 7, & 8 Usage:
|===
|Example |Translation
|...\|ES\|*\|+10^min\|... |translates to: execute this service request the first time without evaluating the condition specified in the TQ2 segment; but repeat only its execution when the specified external service request's start or finish date/time has met this condition. This specification generates a repetition of the service request for each iteration of the cycle.
|===

*Note:* This requires that the requesting application be able to specify the placer/filler/placer group number of the last service request in the cycle in the first service request's quantity/timing specification.
