== OM1.42 - Kind of Quantity Observed (CWE)

[segment-definition]
// TODO: Add field definition

[segment-comment]
Definitions: This optional attribute describes the underlying kind of property represented by this observation. This attribute distinguishes concentrations from total amounts, molar concentrations from mass concentrations, partial pressures from colors, and so forth. These are discussed more fully in the LOINC Users' Manual.footnote:[LOINC Committee. Logical Observation Identifier Names and Codes. Indianapolis: Regenstrief Institute and LOINC Committee, 1995.] They are derived from the approach described in 1995 edition of the IUPAC Silver Book.footnote:[International Union of Pure and Applied Chemistry/International Federation of Clinical Chemistry. The Silver Book: Compendium of terminology and nomenclature of properties in clinical laboratory sciences. Oxford: Blackwell Scientific Publishers, 1995.] These distinctions are used in IUPAC and LOINC standard codes. Defined categories are listed in {{v2-table:0254:Kind of Quantity}} in Chapter 2C, Code Tables.

The distinctions of true quantities in this table are based primarily on dimensional analyses. The table contains a number of "families," those related to simple counts (number, number concentration, etc.), to mass (mass, mass concentration, etc.), to enzyme activity (catalytic content, catalytic concentration, etc.), and molar or equivalents (substance content, substance concentration).

By this classification, a glucose (in the US) would be classed as a mass concentration. A sodium would be classed as a substance concentration. Within the family, a total amount should be described as the unadorned variant; e.g., the property of measure for a patient's weight would be mass, not mass content. Most chemical measures produce concentrations, as exemplified by sodium and glucose. However, a 24-hour urine protein is not a mass concentration, but a mass rate (mass per unit time). The content variants (e.g., mass content, substance content) are used to reflect an amount per mass (usually) of tissue.

This attribute would be valued in a master file only if the service sending the master file classified observations by their principle of measurement.
