== RXO.31 - Mood Code (CNE)

[segment-definition]
This field represents the functional state of the order represented by this segment instance. Refer to {{v2-table:0725:Mood Codes}} in Chapter 2C, Code Tables, for valid values. This field may only be used with new trigger events and new messages from v2.6 onward. When this field is not valued in a message that qualifies, then the value is assumed to be 'EVN'.

[segment-comment]
There may appear to be overlap between this field and _ORC-5 Order Status_. However, the intent of Mood Code is to support the description and documentation of historical events. In this context, Mood codes may clash with Order Status codes, a Mood code may apply for different Order Status values, or this segment may be being used outside of the order paradigm (e.g., in a patient care plan). Moods are meant to change the semantics of clinical data in a message when it is not inferable from the trigger event: when the data can represent a past medication, a future medication (e.g., in a patient care plan), or in a request (e.g., as a reason for referral). The reader is referred to Chapter 12, Patient Care, for further discussion of patient care plans and referrals.

Note: RXO-31 Mood Code was introduced in v2.6 to support Patient Care messaging concepts and constructs. At this time, there are no documented use cases for this field in the context of a pharmacy/treatment orders as described in this chapter. This statement does not preclude the use of RXO-31 in pharmacy messages, but implementers should exercise caution in using this field outside of the Patient Care context until the pharmacy/treatment use cases are established. While a similar note exists for RXO-29 Medication Instance Identifier and RXO-30 Segment Instance Identifier, particular care should be taken with RXO-31 as this could modify the intent of the segment/message and create backward compatibility problems.
