== PRC.2 - Facility ID - PRC (CWE)

[segment-definition]
This field contains the facility of the institution for which this price (for the preceding CDM entry) is valid. For use when needing multi-facility pricing. If null, assume all facilities. In a multi-facility environment, the facility associated with this chargeable item may not be the same as the sending or receiving facility identified in the MSH segment. Use only when the price is not the same for all facilities, that is, a null value indicates that this pricing is valid for all facilities.

[segment-comment]
When two PRC segments are sent with the same key values but different facility identifiers, the second is sent in addition to the first, not to replace the first. The effective unique identifier is the charge code (_PRC-1 - Primary Key Value - PRC_) plus the facility ID (_PRC-2 - Facility ID_). Multiple facility identifiers can be sent in the same segment to indicate that those facilities use the same pricing. Refer to {{v2-table:0464:Facility ID}} in Chapter 2C, Code Tables, for suggested values.
