== OM3.4 - Normal Text/Codes for Categorical Observations (CWE)

[segment-definition]
Certain observations/tests with a nature code of A or C (see _OM1-18 - Nature of Service/Test/Observation_) have text (alpha) results (e.g., reactive, nonreactive). Alpha normals for those tests should be entered in this field (e.g., "nonreactive"). Refer to Table 0654 - Normal Text/Codes for Categorical Observations in Chapter 2C for valid values.

[segment-comment]
The format of this field is:

The first component is a code taken from a standard code source list. The second component is the text associated with the code. The third component is the identification of the code table source. When only a text description of a possible answer is available, it is recorded as ^<text>.

Care should be taken to transmit only those results that are considered normal for that test. A drug screen may have possible results of "negative" and "positive." However, only a result of "negative" is considered to be normal. When an observation has more than one "normal" result, multiple values in this field should be separated with a repeat delimiter.
