== OBX.8 - Interpretation Codes (CWE)

[segment-definition]
One or more codes specifying a categorical assessment of the observation value (OBX.5), such as "Normal", "Abnormal", "Positive", "Negative", "Resistant", "Susceptible", etc.

[segment-comment]
This field may also be used to convey an assessment of an observation where no legitimate result may be obtained. This includes laboratory assays that are rejected due to the presence of interfering substances, specimen toxicity or failure of quality control.

As a CWE data type, this field may be populated with either HL7-defined codes or codes derived from other code systems (such as SNOMED). See {{v2-table:0078:Interpretation Code}} for potential entries.

When the filler can discern the normal status of a textual report, such as chest X-ray reports or microbiologic culture, these should be reported as "N" when normal and "A"when abnormal. Multiple codes, e.g., abnormal and worse, would be separated by a repeat delimiter, e.g., "A~W".

Results may also be reported in *shorthand* by reporting the normalcy status without specifying the exact numeric value of the result. Such shorthand is quite common in clinical notes, where physicians will simply say that *the glucose result was normal.* Such shorthand reporting is also seen in drug experience reporting. In such cases, the result can be reported in the OBX by reporting the interpretation code in _OBX-8-Interpretation Codes_ without specifying any value in _OBX-5-observation value._
