== OBX.22 - Mood Code (CNE)

[segment-definition]
This field identifies the actuality of the observation (e.g., intent, request, promise, event). Refer to {{v2-table:0725:Mood Codes}} for valid values. This field may only be used with new trigger events and new messages from v 2.6 onward. When this field is not valued in a message that qualifies, then the Value is assumed to be 'EVN'.

[segment-comment]
Note: OBX-22 Mood Code was introduced in v 2.6 to support Patient Care messaging concepts and constructs. At this time, there are no documented use cases for this field in the context messages as described in this chapter. This statement does not preclude the use of OBX-22, but implementers should exercise caution in using this field outside of the Patient Care context until appropriate use cases are established. While a similar note exists for OBX-21 Observation Instance Identifier, particular care should be taken with OBX-22 as this could modify the intent of the segment/message and create backward compatibility problems.
