== OBX.3 - Observation Identifier (CWE)

[segment-definition]
This field contains a unique identifier for the observation. The format is that of the Coded Element (CWE). Example: "8625-6^P-R interval^LN". Refer to Table 0622 - Observation Identifier in Chapter 2C for valid values.

[segment-comment]
In most systems the identifier will *point* to a master observation table that will provide other attributes of the observation that may be used by the receiving system to process the observations it receives. A set of message segments for transmitting such master observation tables is described in Chapter 8. The relation of an observation ID to a master observation table is analogous to the relationship between a charge code (in a billing record) and the charge master.

When local codes are used as the first identifier in this field we strongly encourage sending a universal identifier as well to permit receivers to equivalence results from different providers of the same service (e.g., a hospital lab and commercial lab that provides serum potassium to a nursing home). LOINC® is one possible universal and HL7-approved code system for the Observation identifier. It covers observations and measurements, such as laboratory tests, physical findings, radiology studies, and claims attachments. See {{v2-table:0396:Coding System}}, the HL7 www list server and Appendix X2 of ASTM E1467 for neurophysiology tests, or it can be obtained from http://www.regenstrief.org/loinc/loinc.htm[www.regenstrief.org/loinc/loinc.htm].

*The use of suffixes as described in section _7.2.4_ and section _7.2.5_ has been deprecated as of v 2.7.*
