== EI.2 - Namespace ID (IS)

[datatype-definition]
See Section _2A.2.33.1_, "_Namespace ID (IS)_" for definition. 

FIXME - if possible we should just reuse the description from HD.1 as indicated above. As well, it's not clear to me if the note is helpful or not, in large part because "technical committee responsible for that segment" is not clear. Is this part of an implementation process? Can we remove the note?

The assigning authority is a unique identifier of the system (or organization or agency or department) that creates the data. Refer to file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70363[_User-defined Table 0363 – Assigning Authority_] for suggested values.

[NOTE]
When the HD is used as a part of another data type, in this case as part of the EI data type, this table may be re-defined (given a different user-defined table number and name) by the technical committee responsible for that segment. By site agreement, implementers may continue to use file:///E:\V2\v2.9%20final%20Nov%20from%20Frank\V29_CH02C_Tables.docx#HL70300[User-defined Table 0300 – Namespace ID] for the first component

