== OBR.54 - Parent Order (EIP)

[segment-definition]
This field relates a child order to its parent order when a parent child order relationship exists. The parent child order mechanism is described in {{v2-table:0119:Order Control Codes}} in Chapter 2C, Code Tables, under order control code PA. This field uniquely identifies the parent orders; no other information is required to link the child order with its parent orders. It can be used to express that this order is a reflex being a consequence of original results referred here.

[segment-comment]
The first component has the same format as _ORC-2-placer order number_ (Section _link:#_OBR-2___Placer order number   (EI) [*Error! Reference source not found.*],_ "link:#_OBR-2___Placer order number   (EI) [*_Error! Reference source not found._*]"). The second component has the same format as _ORC-3-filler order number_ (Section link:#_OBR-3___Filler Order Number   (EI) [*_Error! Reference source not found._*], "link:#_OBR-3___Filler Order Number   (EI) [*_Error! Reference source not found._*]"). The components of the placer order number and the filler order number are transmitted in sub‑components of the two components of this field.

_Note that ORC-8 – Parent Order is equivalent to OBR-54-Parent Order, but neither one_ is the same as _OBR-29-Parent Result Obersvation Identifier_ .

Condition: Where the message has matching ORC/OBR pairs, ORC-8 and OBR-54 must carry the same value.
