== OBR.47 - Filler Supplemental Service Information (CWE)

[segment-definition]
This field contains supplemental service information sent from the filler system to the placer system for the procedure code reported in _OBR-4 Universal Service ID._ This field will be used to report ordering information detail that is not available in other specific fields in the OBR segment. Typically it will reflect the same information as was sent to the filler system in _OBR-46-Placer supplemental service information_ unless the order was modified, in which case the filler system will report what was actually performed using this field. Multiple supplemental service information elements may be reported. Refer to {{v2-table:0411:Supplemental Service Information Values}} in Chapter 2C, Code Tables.

[segment-comment]
This field can be used to describe details such as whether study is to be done on the right or left, for example, where the study is of the arm and the order master file does not distinguish right from left, or whether the study is to be done with or without contrast (when the order master file does not make such distinctions).
