== TXA.17 - Document Completion Status (ID)

[segment-definition]
This field identifies the current completion state of the document. This is a required, table-driven field. Refer to {{v2-table:0271:Document Completion Status}} for valid values.

[segment-comment]
Figure 9-1. Document completion status state transition table

Figure 9-1. Document completion status state transition table
|===
|Transition (Action) |Old State |New State
a|
T01 Original Notification

T02 Original Notification and Content

|NA a|
Dictated

In Progress

Incomplete

Pre-authenticated

Authenticated

Legally authenticated

a|
T03 Status Change Notification

T04 Status Change Notification and Content

|Dictated a|
In Progress

Incomplete

Pre-authenticated

Authenticated

Legally authenticated

| |In Progress a|
Incomplete

Pre-authenticated

Authenticated

Legally authenticated

| |Incomplete a|
Pre-authenticated

Authenticated

Legally authenticated

| |Pre-authenticated a|
Authenticated

Legally authenticated

| |Authenticated |Legally authenticated
| |Legally authenticated |NA
| |Documented a|
Pre-authenticated

Authenticated

Legally authenticated

a|
T05 Addendum Notification

T06 Addendum Notification and Content

|NA a|
Dictated

In Progress

Incomplete

Pre-authenticated

Authenticated

Legally authenticated

a|
T07 Edit Notification

T08 Edit Notification and Content

|Dictated a|
In Progress

Incomplete

Pre-authenticated

Authenticated

Legally authenticated

| |In Progress a|
Incomplete

Pre-authenticated

Authenticated

Legally authenticated

| |Incomplete a|
Pre-authenticated

Authenticated

Legally authenticated

| |Pre-authenticated a|
Authenticated

Legally authenticated

| |Authenticated |Legally authenticated
| |Legally authenticated |NA
| |Documented a|
Pre-authenticated

Authenticated

Legally authenticated

a|
T09 Replacement Notification

T10 Replacement Notification and Content

|NA a|
Dictated

In Progress

Incomplete

Pre-authenticated

Authenticated

Legally authenticated

|T11 Cancel Notification |Dictated +
In Progress +
Incomplete +
Pre-authenticated +
and Availability status of "Unavailable" |Canceled
|===
