== SPM.11 - Specimen Role (CWE)

[segment-definition]
// TODO: Add field definition

[segment-comment]
This field indicates the role of the sample. Refer to {{v2-table:0369:Specimen role}} for suggested values. Each of these values is normally identifiable by the systems and its components and can influence processing and data management related to the specimen.

If this field is not populated, then the specimen described has no special, or specific, role other than serving as the focus of the observation. Such specimens include patient, environmental and other specimens that are intended for analysis.

A grouped specimen consists of identical specimen types from multiple individuals that do not have individual identifiers and upon which the same services will be performed. If the specimen role value is "G" then the Grouped Specimen Count (_SPM-13_) must be valued with the total number of specimens contained in the group.

If the specimen role is "L", the repetitions of Parent Specimen ID (SPM-4) represent the individual parent specimens that contribute to the pooled specimen.
