== GP2.8 - Modifier Edit Code (CWE)

[segment-definition]
This field contains calculated edits of the modifiers for each line or HCPCS/CPT. This field can be repeated up to five times, one edit for each of the modifiers present. This field relates to the values in link:#pr1-16-procedure-code-modifier-cne-01316[_PR1-16 - Procedure Code Modifier_]. Each repetition corresponds positionally to the order of the PR1-16 modifier codes. If no modifier code exists, use the code "U" (modifier edit code unknown) as a placeholder. The repetitions of Modifier Edit Codes must match the repetitions of Procedure Code Modifiers. For example, if link:#pr1-16-procedure-code-modifier-cne-01316[_PR1-16 - Procedure Code Modifier_] reports ...|01~02~03~04|... as modifier codes, and modifier code 03 modifier status code is unknown, _GP2-8 - Modifier Edit Code_ would report ...|1~1~U~1|... Refer to {{v2-table:0467:Modifier Edit Code}} in Chapter 2C, Code Tables, for suggested values. This field is defined by CMS or other regulatory agencies
